-- groups → ixauth_groups 개명.
--
-- V1~V11 은 고정이다. 이미 배포된 DB 가 그 체크섬을 들고 있으므로 고치면 부팅에 실패한다.
-- 그래서 V1 의 `CREATE TABLE groups` 를 손대지 않고 여기서 이름만 바꾼다.
--
--
-- 왜 PostgreSQL 쪽도 함께 바꾸는가
-- =====================================================================
-- GROUPS 는 MySQL 8.0.2+ 예약어다(윈도우 함수 절). PostgreSQL·MariaDB 에서는 예약어가
-- 아니므로 이 방언만 놓고 보면 바꿀 이유가 없다. 그런데 표 이름을 정하는 것은 방언별
-- 마이그레이션이 아니라 **엔티티 하나**(domain/Group.java)이고, 그 하나가 세 방언을
-- 함께 탄다. 방언마다 다른 이름을 쓰려면 @Table 을 방언별로 갈라야 하는데, 그러면
-- 네이티브 SQL·조인 이름까지 전부 갈라진다. 이름은 한 벌이어야 한다.
--
-- DDL 만 백틱으로 감싸는 우회를 택하지 않은 이유 — Hibernate 가 런타임 SELECT/INSERT
-- 에서 같은 이름을 인용 없이 내보내므로 그룹을 읽는 경로가 전부 깨진다.
-- hibernate.globally_quoted_identifiers 는 PostgreSQL 의 소문자 폴딩 규약과 충돌해
-- 이미 배포된 두 설치본을 위험에 빠뜨린다 (2026-08-21, 늘봄 PoC 이슈 ①).
--
--
-- 기존 설치본에 미치는 영향
-- =====================================================================
-- PostgreSQL 은 외래키·인덱스·시퀀스가 표를 OID 로 따라가므로 RENAME 하나면 끝난다.
-- user_groups.group_id · group_roles.group_id 의 FK 는 그대로 유효하다.
-- 데이터는 한 줄도 움직이지 않는다.
ALTER TABLE groups RENAME TO ixauth_groups;
