-- ============================================================================
-- V1__baseline.sql — IX-Trust 운영 스키마 baseline (HomeLab 2026-04-28 snapshot)
-- ============================================================================
-- 운영 DB(HomeLab .81 / ProstLab .153)는 Flyway 도입 첫 부팅 시 baseline-on-migrate=true
-- 설정에 의해 V1=SUCCESS 만 기록되고 본 SQL은 실행되지 않는다.
-- 새로 부트스트랩하는 dev/staging 환경에서만 V1이 실제 실행되어 스키마를 만든다.
--
-- ddl-auto=update 와 공존: NOT NULL 컬럼 추가 등 update 가 못 하는 변경만 V2+ 로 명시.
-- 향후 양쪽 운영 DB 완전 동기화 후 ddl-auto=validate 전환 예정.
-- ============================================================================


CREATE TABLE public.audit_logs (
    id bigint NOT NULL,
    actor_email character varying(255),
    actor_id bigint,
    actor_type character varying(20),
    correlation_id character varying(100),
    created_at timestamp(6) without time zone NOT NULL,
    description text,
    error_message text,
    event_type character varying(100) NOT NULL,
    ip_address character varying(45),
    metadata text,
    new_values text,
    old_values text,
    resource_id bigint,
    resource_name character varying(255),
    resource_type character varying(50),
    severity character varying(20) NOT NULL,
    status character varying(20) NOT NULL,
    tenant_id bigint NOT NULL,
    user_agent text
);

ALTER TABLE public.audit_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.data_sources (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    base_dn character varying(500),
    bind_dn character varying(500),
    bind_password character varying(500),
    enabled boolean NOT NULL,
    field_mappings text,
    host character varying(255),
    jdbc_driver character varying(255),
    jdbc_password character varying(500),
    jdbc_query text,
    jdbc_url character varying(1000),
    jdbc_username character varying(255),
    last_sync_at timestamp(6) without time zone,
    name character varying(255) NOT NULL,
    port integer,
    sync_message text,
    sync_status character varying(20),
    tenant_id bigint NOT NULL,
    type character varying(20) NOT NULL,
    user_search_base character varying(500),
    user_search_filter character varying(500),
    sync_schedule character varying(20),
    sync_schedule_time character varying(5)
);

ALTER TABLE public.data_sources ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.data_sources_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.departments (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    active boolean NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(255) NOT NULL,
    parent_id bigint,
    sort_order integer NOT NULL,
    tenant_id bigint NOT NULL,
    description character varying(500)
);

ALTER TABLE public.departments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.departments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.identity_providers (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    attribute_mappings text,
    authorization_uri character varying(1000),
    auto_link boolean NOT NULL,
    button_color character varying(20),
    button_label character varying(100),
    client_id character varying(500) NOT NULL,
    client_secret character varying(1000),
    create_user boolean NOT NULL,
    default_roles character varying(500),
    display_name character varying(200) NOT NULL,
    display_order integer,
    enabled boolean NOT NULL,
    icon_url character varying(500),
    issuer_uri character varying(1000),
    jwk_set_uri character varying(1000),
    provider_type character varying(50) NOT NULL,
    registration_id character varying(100) NOT NULL,
    require_mfa boolean NOT NULL,
    scopes character varying(500),
    tenant_id bigint NOT NULL,
    token_uri character varying(1000),
    trust_email boolean NOT NULL,
    user_info_uri character varying(1000),
    user_name_attribute character varying(100),
    icon_data bytea,
    icon_content_type character varying(100),
    button_text_color character varying(20)
);

ALTER TABLE public.identity_providers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.identity_providers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.oauth2_authorization (
    id character varying(100) NOT NULL,
    registered_client_id character varying(100) NOT NULL,
    principal_name character varying(200) NOT NULL,
    authorization_grant_type character varying(100) NOT NULL,
    authorized_scopes character varying(1000) DEFAULT NULL::character varying,
    attributes text,
    state character varying(500) DEFAULT NULL::character varying,
    authorization_code_value text,
    authorization_code_issued_at timestamp with time zone,
    authorization_code_expires_at timestamp with time zone,
    authorization_code_metadata text,
    access_token_value text,
    access_token_issued_at timestamp with time zone,
    access_token_expires_at timestamp with time zone,
    access_token_metadata text,
    access_token_type character varying(100) DEFAULT NULL::character varying,
    access_token_scopes character varying(1000) DEFAULT NULL::character varying,
    oidc_id_token_value text,
    oidc_id_token_issued_at timestamp with time zone,
    oidc_id_token_expires_at timestamp with time zone,
    oidc_id_token_metadata text,
    refresh_token_value text,
    refresh_token_issued_at timestamp with time zone,
    refresh_token_expires_at timestamp with time zone,
    refresh_token_metadata text,
    user_code_value text,
    user_code_issued_at timestamp with time zone,
    user_code_expires_at timestamp with time zone,
    user_code_metadata text,
    device_code_value text,
    device_code_issued_at timestamp with time zone,
    device_code_expires_at timestamp with time zone,
    device_code_metadata text
);

CREATE TABLE public.oauth2_authorization_consent (
    registered_client_id character varying(100) NOT NULL,
    principal_name character varying(200) NOT NULL,
    authorities character varying(1000) NOT NULL
);

CREATE TABLE public.oauth_clients (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    active boolean NOT NULL,
    client_id character varying(255) NOT NULL,
    client_name character varying(255) NOT NULL,
    client_secret character varying(255) NOT NULL,
    grant_types character varying(255) NOT NULL,
    redirect_uris character varying(255) NOT NULL,
    scopes character varying(255) NOT NULL,
    tenant_id bigint NOT NULL,
    health_check_url character varying(255),
    actuator_base_path character varying(100),
    actuator_token character varying(500),
    back_channel_logout_uri character varying(500),
    description character varying(255),
    post_logout_redirect_uris character varying(255),
    registered_id character varying(255),
    require_pkce boolean DEFAULT true NOT NULL,
    require_consent boolean DEFAULT true NOT NULL,
    service_api_key character varying(500),
    saml_acs_url character varying(500),
    saml_entity_id character varying(500),
    saml_metadata_url character varying(500),
    saml_slo_url character varying(500),
    saml_enabled boolean DEFAULT false NOT NULL,
    service_url character varying(500),
    event_webhook_uri character varying(500),
    external_domain character varying(255),
    maintenance_end_time character varying(64),
    maintenance_message text,
    maintenance_active boolean DEFAULT false NOT NULL,
    mfa_required boolean DEFAULT false NOT NULL,
    brand_color character varying(7),
    display_name character varying(100),
    icon_url character varying(500),
    display_order integer DEFAULT 0 NOT NULL,
    picker_visible boolean DEFAULT true NOT NULL
);

ALTER TABLE public.oauth_clients ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.oauth_clients_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.password_reset_tokens (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    email character varying(255) NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    token character varying(255) NOT NULL,
    used boolean NOT NULL
);

ALTER TABLE public.password_reset_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.password_reset_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.positions (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    active boolean NOT NULL,
    code character varying(50) NOT NULL,
    description character varying(500),
    grade integer NOT NULL,
    name character varying(255) NOT NULL,
    tenant_id bigint NOT NULL
);

ALTER TABLE public.positions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.positions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.push_subscriptions (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    auth text NOT NULL,
    endpoint text NOT NULL,
    endpoint_hash character varying(64) NOT NULL,
    failure_count integer NOT NULL,
    last_used_at timestamp(6) without time zone,
    p256dh text NOT NULL,
    tenant_id bigint,
    user_agent character varying(255),
    user_id bigint NOT NULL
);

ALTER TABLE public.push_subscriptions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.push_subscriptions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.roles (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    built_in boolean NOT NULL,
    code character varying(50) NOT NULL,
    description character varying(500),
    name character varying(255) NOT NULL,
    permissions character varying(2000),
    tenant_id bigint NOT NULL
);

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.sso_session_bindings (
    id bigint NOT NULL,
    client_id character varying(100) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    sid character varying(64) NOT NULL,
    sub character varying(255) NOT NULL
);

ALTER TABLE public.sso_session_bindings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sso_session_bindings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.sso_settings (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    category character varying(255) NOT NULL,
    default_value character varying(255),
    description character varying(255),
    setting_key character varying(255) NOT NULL,
    sort_order integer,
    setting_value text,
    value_type character varying(255) NOT NULL
);

ALTER TABLE public.sso_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sso_settings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.tenants (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    active boolean NOT NULL,
    domain character varying(255) NOT NULL,
    logo_url character varying(255),
    name character varying(255) NOT NULL
);

ALTER TABLE public.tenants ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tenants_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.user_identity_links (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    external_email character varying(500),
    external_name character varying(200),
    external_profile_image character varying(1000),
    external_user_id character varying(500) NOT NULL,
    identity_provider_id bigint NOT NULL,
    last_login_at timestamp(6) without time zone,
    user_id bigint NOT NULL
);

ALTER TABLE public.user_identity_links ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_identity_links_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.user_roles (
    user_id bigint NOT NULL,
    role_id bigint NOT NULL
);

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    active boolean NOT NULL,
    department_id bigint,
    email character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    tenant_id bigint NOT NULL,
    position_id bigint,
    address character varying(255),
    display_name character varying(255),
    employee_number character varying(10),
    job_description character varying(255),
    phone_number character varying(255),
    photo bytea,
    backup_codes text,
    locked_until timestamp(6) without time zone,
    totp_secret character varying(64),
    failed_attempts integer DEFAULT 0 NOT NULL,
    totp_enabled boolean DEFAULT false NOT NULL,
    address_detail character varying(255),
    zip_code character varying(10),
    auth_method character varying(20) DEFAULT 'LOCAL'::character varying NOT NULL
);

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.data_sources
    ADD CONSTRAINT data_sources_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT departments_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.identity_providers
    ADD CONSTRAINT identity_providers_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT idx_prt_token UNIQUE (token);

ALTER TABLE ONLY public.oauth2_authorization_consent
    ADD CONSTRAINT oauth2_authorization_consent_pkey PRIMARY KEY (registered_client_id, principal_name);

ALTER TABLE ONLY public.oauth2_authorization
    ADD CONSTRAINT oauth2_authorization_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.oauth_clients
    ADD CONSTRAINT oauth_clients_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.positions
    ADD CONSTRAINT positions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.push_subscriptions
    ADD CONSTRAINT push_subscriptions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.sso_session_bindings
    ADD CONSTRAINT sso_session_bindings_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.sso_settings
    ADD CONSTRAINT sso_settings_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tenants
    ADD CONSTRAINT tenants_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT uk6pemxu2q2c256m1uxg3ypj08v UNIQUE (tenant_id, code);

ALTER TABLE ONLY public.oauth_clients
    ADD CONSTRAINT uk6xt89c581inu4wo01bwyk4pqy UNIQUE (registered_id);

ALTER TABLE ONLY public.positions
    ADD CONSTRAINT uk8h6s9uwsj71d8ookgdpukfb3h UNIQUE (tenant_id, code);

ALTER TABLE ONLY public.push_subscriptions
    ADD CONSTRAINT uk_push_subscriptions_endpoint_hash UNIQUE (endpoint_hash);

ALTER TABLE ONLY public.user_identity_links
    ADD CONSTRAINT uk_uil_provider_external UNIQUE (identity_provider_id, external_user_id);

ALTER TABLE ONLY public.oauth_clients
    ADD CONSTRAINT ukaaedvpdimcfvgse9vihrb7n7l UNIQUE (client_id);

ALTER TABLE ONLY public.tenants
    ADD CONSTRAINT ukehgpgu3yilhiprwm3wbipxt43 UNIQUE (domain);

ALTER TABLE ONLY public.identity_providers
    ADD CONSTRAINT ukgqoosbjlvb667moryibc5253a UNIQUE (registration_id);

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT uko2mx37j2nytheau7lrm29n7cy UNIQUE (tenant_id, code);

ALTER TABLE ONLY public.sso_settings
    ADD CONSTRAINT ukqgvpyv235l5ypl218e8yd5xny UNIQUE (setting_key);

ALTER TABLE ONLY public.user_identity_links
    ADD CONSTRAINT user_identity_links_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

CREATE INDEX idx_audit_actor ON public.audit_logs USING btree (actor_id, created_at DESC);

CREATE INDEX idx_audit_correlation ON public.audit_logs USING btree (correlation_id);

CREATE INDEX idx_audit_resource ON public.audit_logs USING btree (resource_type, resource_id);

CREATE INDEX idx_audit_severity ON public.audit_logs USING btree (severity, created_at DESC);

CREATE INDEX idx_audit_tenant_event_time ON public.audit_logs USING btree (tenant_id, event_type, created_at DESC);

CREATE INDEX idx_idp_enabled ON public.identity_providers USING btree (enabled);

CREATE INDEX idx_idp_tenant_id ON public.identity_providers USING btree (tenant_id);

CREATE INDEX idx_prt_email ON public.password_reset_tokens USING btree (email);

CREATE INDEX idx_push_subscriptions_user_id ON public.push_subscriptions USING btree (user_id);

CREATE INDEX idx_sso_session_bindings_sid ON public.sso_session_bindings USING btree (sid);

CREATE INDEX idx_sso_session_bindings_sub ON public.sso_session_bindings USING btree (sub);

CREATE INDEX idx_uil_provider_external ON public.user_identity_links USING btree (identity_provider_id, external_user_id);

CREATE INDEX idx_uil_user_id ON public.user_identity_links USING btree (user_id);

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkh8ciramu9cc9q3qcqiv4ue8a6 FOREIGN KEY (role_id) REFERENCES public.roles(id);

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES public.users(id);


-- ============================================================================
-- Spring Authorization Server JDBC 스키마 (기존 schema.sql 흡수)
-- ============================================================================

-- Spring Authorization Server JDBC 스키마 (PostgreSQL)
-- oauth2_registered_client는 JpaRegisteredClientRepository로 대체 (oauth_clients 단일 테이블)

CREATE TABLE IF NOT EXISTS oauth2_authorization (
    id varchar(100) NOT NULL,
    registered_client_id varchar(100) NOT NULL,
    principal_name varchar(200) NOT NULL,
    authorization_grant_type varchar(100) NOT NULL,
    authorized_scopes varchar(1000) DEFAULT NULL,
    attributes text DEFAULT NULL,
    state varchar(500) DEFAULT NULL,
    authorization_code_value text DEFAULT NULL,
    authorization_code_issued_at timestamptz DEFAULT NULL,
    authorization_code_expires_at timestamptz DEFAULT NULL,
    authorization_code_metadata text DEFAULT NULL,
    access_token_value text DEFAULT NULL,
    access_token_issued_at timestamptz DEFAULT NULL,
    access_token_expires_at timestamptz DEFAULT NULL,
    access_token_metadata text DEFAULT NULL,
    access_token_type varchar(100) DEFAULT NULL,
    access_token_scopes varchar(1000) DEFAULT NULL,
    oidc_id_token_value text DEFAULT NULL,
    oidc_id_token_issued_at timestamptz DEFAULT NULL,
    oidc_id_token_expires_at timestamptz DEFAULT NULL,
    oidc_id_token_metadata text DEFAULT NULL,
    refresh_token_value text DEFAULT NULL,
    refresh_token_issued_at timestamptz DEFAULT NULL,
    refresh_token_expires_at timestamptz DEFAULT NULL,
    refresh_token_metadata text DEFAULT NULL,
    user_code_value text DEFAULT NULL,
    user_code_issued_at timestamptz DEFAULT NULL,
    user_code_expires_at timestamptz DEFAULT NULL,
    user_code_metadata text DEFAULT NULL,
    device_code_value text DEFAULT NULL,
    device_code_issued_at timestamptz DEFAULT NULL,
    device_code_expires_at timestamptz DEFAULT NULL,
    device_code_metadata text DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS oauth2_authorization_consent (
    registered_client_id varchar(100) NOT NULL,
    principal_name varchar(200) NOT NULL,
    authorities varchar(1000) NOT NULL,
    PRIMARY KEY (registered_client_id, principal_name)
);
